site_name: "node-red-contrib-letsfiware-NGSI"
site_description: node-red-contrib-letsfiware-NGSI (Let's FIWARE)

nav:
  - 'Home':
    - 'Index': index.md
    - 'Installation': installation.md
    - 'Tutorial': tutorial.md
    - 'Custom nodes':
      - 'NGSI Entity': custom_nodes/ngsi_entity.md
      - 'NGSI Source': custom_nodes/ngsi_source.md
      - 'NGSI Batch update': custom_nodes/ngsi_batch_update.md
      - 'NGSI Subscription': custom_nodes/ngsi_subscription.md
      - 'NGSI to Worldmap': custom_nodes/ngsi_to_worldmap.md
      - 'NGSI GTFS realtime': custom_nodes/ngsi_gtfs_realtime.md
      - 'NGSI Open APIs': custom_nodes/ngsi_open-apis.md
