name: Close inactive issues
on:
  schedule:
    - cron: "18 18 * * *"

jobs:
  close-issues:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v8
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-message: "This issue is stale because it has been open for 14 days with no activity."
          close-issue-message: "This issue was closed because it has been inactive for 7 days since being marked as stale."
          stale-issue-label: "stale"
          exempt-issue-labels: 'bug,enhancement'
          days-before-issue-stale: 14
          days-before-issue-close: 7
          days-before-pr-stale: -1
          days-before-pr-close: -1
